### ISSUE TITLE
Integration with spec2scl

### ISSUE THREAD

**Issue by irushchyshyn** [fedora-python/pyp2rpm#100]
Integrate [spec2scl](https://github.com/sclorg/spec2scl/) to enable the user to create an SCL-style spec file for a PyPI package.

There should be an option (e.g. `--sclize`) to convert tags and macro definitions and produce a Software Collection spec file. The user should be able to provide optional arguments defined for `spec2scl`.
The implementation will require introducing a dependency on  [spec2scl](https://github.com/sclorg/spec2scl/).

**Comment by hroncok** [comment]
Note: It can be optional dependency and the feature will simply not be available if spec2scl is not installed.

**Comment by irushchyshyn** [comment]
That is a very good suggestion, thanks @hroncok
