### ISSUE TITLE
FTA for tagged release?

### ISSUE THREAD

**Issue by joequant** [fedora-python/pyp2rpm#11]
Hi,

Is there any FTA for a tagged release?

I'd like to package this for mageia, but it would help to have a tagged release to checkpoint against.

**Comment by sYnfo** [comment]
There are tags in the original repository [0], but we've recently move to github and it looks like the tags did not get created properly. For now, if you need a specific commit you can take it from there, or you can just grab the newest release on pypi [1]. Is that solution good enough for you? :)

[0] https://bitbucket.org/bkabrda/pyp2rpm/downloads
[1] https://pypi.python.org/pypi/pyp2rpm

**Comment by hroncok** [comment]
@sYnfo I've just pushed the tags.

**Comment by sYnfo** [comment]
Cool, thanks Miro.
