### ISSUE TITLE
default savedir to %{_topdir}

### ISSUE THREAD

**Issue by brianjmurrell** [fedora-python/pyp2rpm#117]
It would be useful, I think, to default the _SAVE_DIR_ (-d) value to the RPM `%{topdir}` macro's value on the system it's running on.

**Comment by irushchyshyn** [comment]
Reopening the issue to use `rpm --eval %{_topdir}`  (see [comment](https://github.com/fedora-python/pyp2rpm/commit/92e992988c1f77acd531e306e7158662f4c9021d#commitcomment-24091727))
