### ISSUE TITLE
Empty tag: Source0:

### ISSUE THREAD

**Issue by brianjmurrell** [fedora-python/pyp2rpm#118]
If I create a specfile from a local file the `Source0:` tag is empty:

```
$ pyp2rpm -d ~/rpm/ ~/greenlet-0.4.2.zip > ~/rpm/SPECS/python-greenlet.spec
Failed to synchronize cache for repo 'foo', disabling.
$ rpmbuild -bb --define '_sourcedir /home/brian/' ~/rpm/SPECS/python-greenlet.spec
error: line 11: Empty tag: Source0:
$ grep Source0 ~/rpm/SPECS/python-greenlet.spec
Source0:        
```

**Comment by irushchyshyn** [comment]
Thanks for reporting this @brianjmurrell .

I would like to clarify though, what is the expected behaviour in this example? I suppose it should be set to the local file name:
```
Source0: greenlet-0.4.2.zip
```

**Comment by brianjmurrell** [comment]
I think so.  Or perhaps a pypi name should be derived from the file?  Or maybe it should just be an outright error to try to use a local file?

I would think any of those, or perhaps even another solution other than generating a broken specfile.

**Comment by brianjmurrell** [comment]
Awesome.  Thanks!
