### ISSUE TITLE
generated only-python3 specfile

### ISSUE THREAD

**Issue by brianjmurrell** [fedora-python/pyp2rpm#122]
Using pyp2rpm on [httpagentparser-1.5.0)](https://pypi.python.org/pypi/httpagentparser/1.5.0) I get a specfile that only seems to be building the python3 variant of that package.  The command I used to build the spec was:

```
$ pyp2rpm -t epel7 httpagentparser-1.5.0.tar.gz > python-httpagentparser.spec
```

**Comment by hroncok** [comment]
That package only supports Python 3 according to the classifiers.

https://github.com/shon/httpagentparser/blob/8bfc1c9b393d83da5544f392bbbe57cf7e7d2ff3/setup.py#L51

According to the README, it supports 2.5+ as well. Please open an issue in https://github.com/shon/httpagentparser

**Comment by brianjmurrell** [comment]
Ahh.  Thanks.  Learned something new about Python software distribution today.  [Ticket](https://github.com/shon/httpagentparser/issues/73) filed.

**Comment by brianjmurrell** [comment]
~~So in a case like this, I guess there is no switch (or other way) to force `pyp2rpm` to build a specfile (i.e. while waiting for upstream to fix) for Python 2.x is there?~~

Never mind.  I found `-p`

**Comment by shon** [comment]
Fixed this issue in httpagentparser
