### ISSUE TITLE
deal with packages that interchange _ and - in their names

### ISSUE THREAD

**Issue by brianjmurrell** [fedora-python/pyp2rpm#123]
There is a [package](https://pypi.python.org/pypi/sphinx_py3doc_enhanced_theme) in which has underscores (_) in it's name but in the tarball the underscores are actually dashes (-).

pyp2rpm is (understandably) getting confused by this.  I wonder if anything can be done to figure this out.

It works fine of course if I point pyp2rpm at a downloaded tarball of the above, but that then leads to #118.

**Comment by irushchyshyn** [comment]
Thanks for reporting the issue.

This should be fixed in #98 and the fix is available starting version 3.2.2. Can you please let us know which `pyp2rpm` version you are using to reproduce this?

**Comment by brianjmurrell** [comment]
I'm using whatever is in Fedora Copr currently.  I don't seem to be able to find a version for it in any logs though.

**Comment by irushchyshyn** [comment]
You may find the version in the first line of the generated spec file, as in  `# Created by pyp2rpm-3.2.2`.
COPR probably still uses 3.2.1.

**Comment by mcyprian** [comment]
pyp2rpm inside COPR was updated to version 3.2.2, this is no longer an issue.
