### ISSUE TITLE
Non-python Requires

### ISSUE THREAD

**Issue by marhag87** [fedora-python/pyp2rpm#125]
Is it possible to specify a requirement that is not a python package? I have built a python module that uses xdotool, so I need it as a requirement i the spec file, but I found no way to specify this in the setup.py file.

**Comment by hroncok** [comment]
I don't think so, you would need to add the requirements to the spec file manually.

**Comment by marhag87** [comment]
I guess I won't be able to use the PyPI source type in copr then, that's a shame :(
Thanks for the answer!
