### ISSUE TITLE
Localized date in %changelog

### ISSUE THREAD

**Issue by hroncok** [fedora-python/pyp2rpm#126]
```console
$ locale
LANG=cs_CZ.utf8
LC_CTYPE="cs_CZ.utf8"
LC_NUMERIC="cs_CZ.utf8"
LC_TIME="cs_CZ.utf8"
LC_COLLATE="cs_CZ.utf8"
LC_MONETARY="cs_CZ.utf8"
LC_MESSAGES="cs_CZ.utf8"
LC_PAPER="cs_CZ.utf8"
LC_NAME="cs_CZ.utf8"
LC_ADDRESS="cs_CZ.utf8"
LC_TELEPHONE="cs_CZ.utf8"
LC_MEASUREMENT="cs_CZ.utf8"
LC_IDENTIFICATION="cs_CZ.utf8"
LC_ALL=

$ ./mybin.py -b 3 blurb
...
%changelog
* Čt čen 29 2017 Miro Hrončok <mhroncok@redhat.com> - 1.0.0.post1-1
- Initial package.
```

This is on Fedora 26. i don't think it happened before on Fedora 25.

**Comment by mcyprian** [comment]
I cannot reproduce this for some reason. I am running F26 and my locale output is exactly the same ^^.

**Comment by hroncok** [comment]
You mean you cannot?

**Comment by mcyprian** [comment]
Yes, of course.

**Comment by hroncok** [comment]
Funny enough, I can reproduce, but running he code that produces this isolated, will not reproduce:

```pycon
>>> import time
>>> time.strftime('%a %b %d %Y', time.gmtime())
'Tue Jul 18 2017'
```

**Comment by hroncok** [comment]
So for some reason, when I put this in front of that call:

```python
print(locale.getlocale(locale.LC_TIME))
```

It gives me `('cs_CZ', 'UTF-8')`. I don't know when this is being taken from, but it can be reset fairly simple, PR will follow.
