### ISSUE TITLE
Make Python 3 a default version?

### ISSUE THREAD

**Issue by irushchyshyn** [fedora-python/pyp2rpm#138]
Currently Python 2  is  a [DEFAULT_PYTHON_VERSION](https://github.com/fedora-python/pyp2rpm/blob/master/pyp2rpm/settings.py#L8), and Python 3 is an additional default. Should not it be the other way round already?

```
./mybin.py --help
...
  -b BASE_PYTHON          Base Python version to package for (default: "2").
  -p PYTHON_VERSIONS      Additional Python versions to include in the
                          specfile (e.g -p3 for %{?with_python3}).Can be
                          specified multiple times (default: "3"). Specify
                          additional version or use -b explicitly to disable
                          default.
...
```

**Comment by mcyprian** [comment]
Thanks for opening this, I guess that after switching to versioned prefixes for python2 dependencies #129 and change of executable handling proposed in #137 it should be relatively easy to finally change DEFAULT_PYTHON_VERSION to Python 3. Templates will need to be slightly redesigned to keep usual order of subpackages (python2 subpackage first) in the spec file.
