### ISSUE TITLE
setup.py not found when trying pyp2rpm on jrti-game

### ISSUE THREAD

**Issue by encukou** [fedora-python/pyp2rpm#145]
I tried pyp2rpm on my package, `jrti_game`, without success:

```
$ pyp2rpm jrti_game
Package "jrti_game" could not be found on PyPI.
$ pyp2rpm jrti-game
setup.py not found, maybe local_file is not proper source archive.
```

I believe it may have to do with package name normalization, see https://github.com/fedora-python/pyp2rpm/issues/144

(Also, what's `local_file`?)

**Comment by irushchyshyn** [comment]
I believe the following case was fixed in #98 and is available starting version 3.2.2.

> pyp2rpm jrti-game
> setup.py not found, maybe local_file is not proper source archive.

Which version of pyp2rpm was used?

**Comment by encukou** [comment]
I see! I use the version in Fedora 26.
```
pyp2rpm-3.2.1-3.fc26.noarch
```

It works with the pip-installed one. Sorry for the noise!

**Comment by irushchyshyn** [comment]
> (Also, what's local_file?)

Good question:)
