### ISSUE TITLE
For Fedora, consider making Python 3 only the default

### ISSUE THREAD

**Issue by hroncok** [fedora-python/pyp2rpm#163]
Currently, when pyp2rpm is used without any switches, it creates a combined py3+py2 package. I was wondering whether we are at a point where python2 subpackage would only be created when explicitly asked for (or when pyp2rpm determines the package is py2 only).

I think there are packagers that simply include the python2 subpackage because it was created automatically, even if they don't actually need one. Those who need it would simply use the appropriate switch (`-p2`).

Thoughts?

**Comment by Conan-Kudo** [comment]
This would be good for Fedora and Mageia, as we're considering the same change in Mageia, too.

However, I think this would require some coordination to figure out what to do about unversioned Python package names.

**Comment by irushchyshyn** [comment]
This has been fixed for Fedora and Mageia. And I will do another release for it.
Closing, please reopen if needed.
