### ISSUE TITLE
.egg-info files not found

### ISSUE THREAD

**Issue by dl1chb** [fedora-python/pyp2rpm#175]
Hi,
I am having several issues building packages (scikit-rf and fenics-ffc) on Fedora 28 using mock which might be the same ones like #85 . After editing the SPEC files to disable all documentation builds I tried to build the example (kaptan) shown at the main page of this project. Since I needed pyyaml as an dependency, I tried to build it first (without modifying anything). It says one file is missing:
File not found: /builddir/build/BUILDROOT/python-pyyaml-3.13-1.fc28.x86_64/usr/lib64/python3.6/site-packages/pyyaml-3.13-py?.?.egg-info

I looked at all other python modules I tried to build and it seems every time the .egg-info file is missing. The "?" look like something went wrong by specifying the correct path variables. Has anyone the same issue? I am not sure if it is a bug of pyp2rpm or I am doing something wrong.

Thanks for any help!

Beckus

**Comment by hroncok** [comment]
I don't understand the exact steps that lead to: `File not found: /builddir/build/BUILDROOT/python-pyyaml-3.13-1.fc28.x86_64/usr/lib64/python3.6/site-packages/pyyaml-3.13-py?.?.egg-info`

Are you building your own pyyaml? Why?

**Comment by dl1chb** [comment]
I did exactly as in the example video for katan showed. Just to be sure, my toolchain works. But there where two unsatisfied dependencies: python3dist(pyyaml) and python3dist(pytest). I used a fresh mock install for that, just to be sure. So I started to build pyyaml since it could not be resolved. I see now, that it is in the repos, but not found using the generated SRPM from the pyp2rpm spec-file and mock.

**Comment by hroncok** [comment]
python3dist(pyyaml) is provided by python3-pyyaml-4.2-0.1.b4.fc29.

python3dist(pytest) is provided by python3-pytest-3.6.3-2.fc29.

Maybe that was some temporary issue?

**Comment by dl1chb** [comment]
Hm, python3-PyYAML is also available on fc28, too. Don't know, why it isn't found inside mock. I will try some other things tomorrow, perhaps I can find what is going wrong.

**Comment by hroncok** [comment]
I have an idea:

does the generated pyyaml spec has `BuildRequires: python3-setuptools` (or similar)?

If not, does adding that solve the `File not found:... pyyaml-3.13-py?.?.egg-info` problem?

**Comment by dl1chb** [comment]
It didn't! I added it and now, there is a different error: the required versions of pyyaml could not be found. After removing the restriction of the versions, it installs all dependencies. Of course, it cannot build, because the installed version of pyyaml is the wrong one. But I think this is a different issue, maybe not a fault of pyp2rpm.

Thanks for the help!
