### ISSUE TITLE
Fetch tarball feature request

### ISSUE THREAD

**Issue by nkadel** [fedora-python/pyp2rpm#184]
Please provide a "fetch" feature to download the relevant tarball from pypi.org. The Source is listed in the .spec file, but would have to be re-assembled from the Version and pypi_name macros to request with a manual "curl" or "wget" command.

**Comment by hroncok** [comment]
Note that this project is on life support. I will not be available to provide this feature. Frankly, I don't even understand why pyp2rpm should do this, it downloads the sources as it creates the package.

If you need to download a source from already existing spec, use `spectool -G xxx.spec` from the `rpmdevtools` package.
