### ISSUE TITLE
3.3.4 doesn't find a prerelease passed as vesion unless --prerelease is passed

### ISSUE THREAD

**Issue by evgeni** [fedora-python/pyp2rpm#243]
since the introduction of `--prerelease` one has to pass it even if `-v` already got a fixed prerelease version.

I think `--prerelease` should only affect "search the latest release" and not "use this fixed version" codepaths.

example:

```console
% ./mybin.py -v 4.2.0rc1 galaxy-ng
Package "galaxy-ng" could not be found on PyPI.

% ./mybin.py -v 4.2.0rc1 --prerelease galaxy-ng
# Created by pyp2rpm-3.3.4
%global pypi_name galaxy-ng
…
```

**Comment by gordonmessmer** [comment]
This should be fixed in #245
