### ISSUE TITLE
support for rhel/centos distrubutions [feature proposal]

### ISSUE THREAD

**Issue by marbu** [fedora-python/pyp2rpm#25]
I would be nice if pyp2rpm could create spec files following packaging policies for rhel/centos 6 and 7 distributions. Even though those packaging policies are based on older fedora ones, I'm not sure if just adding proper template would be enough.

How is building packages for rhel/centos connected to fedora? Here is the use case I have in mind:
author of new python module would like to build packages for centos and fedora in copr. Note that copr can build packages for rhel/centos even though it's a fedora project.

**Comment by marbu** [comment]
Any thoughts there?

**Comment by Conan-Kudo** [comment]
@marbu I think this would be quite desirable to have, especially with the new guidelines for actually supporting Python 2 and Python 3 (which is somewhat complex).

Why don't you go ahead and make a pull request to add an EPEL template?

**Comment by marbu** [comment]
I wonder if it would be possible for the suggested _global solution_ fom issue #22 to handle proposed EPEL support as well. Direct dnf query is not an option, moreover most packages are not build in Fedora infactructure unless a package is part of the EPEL directly, so it's not clear which system to query. Eg.  [python-markupsafe](https://apps.fedoraproject.org/packages/python-markupsafe) is available in EPEL 5, but for EPEL 6 and 7 (as it's directly available in core repositories).
