### ISSUE TITLE
pyp2rpm defaults to old version of xml-preferences

### ISSUE THREAD

**Issue by barry-scott** [fedora-python/pyp2rpm#251]
xml-preferences has been at version 1.1.4 for a long time,
I did update it to xml-preferences 1.1.5 today.

But I'm surprised that 1.1.0 is the version that is downloaded.

$ pyp2rpm xml-preferences --srpm 
INFO  Pyp2rpm initialized.
INFO  Using /home/barry/rpmbuild.d/k/SOURCES as directory to save source.
INFO  Downloaded package from PyPI: /home/barry/rpmbuild.d/k/SOURCES/xml-preferences-1.1.0.tar.gz.
INFO  Getting metadata from setup.py using SetupPyMetadataExtractor.

Use -v 1.1.5 I get the latest version.

**Comment by gordonmessmer** [comment]
I've started a fix in #254 , but I think this could use some unit tests before merging.
