### ISSUE TITLE
One log is output in b' bytes ' and contains \n

### ISSUE THREAD

**Issue by barry-scott** [fedora-python/pyp2rpm#252]
$ pyp2rpm xml-preferences --srpm -v 1.1.5
INFO  Pyp2rpm initialized.
INFO  Using /home/barry/rpmbuild.d/k/SOURCES as directory to save source.
INFO  Downloaded package from PyPI: /home/barry/rpmbuild.d/k/SOURCES/xml-preferences-1.1.5.tar.gz.
INFO  Getting metadata from setup.py using SetupPyMetadataExtractor.
INFO  Running extract_dist command with: /usr/bin/python3
WARNING  Template: fedora.spec was not found in /home/barry/Projects/BarrysEmacs/Builder/fedora.spec using default template dir.
INFO  Using default template: fedora.spec.
INFO  Using name: python-xml-preferences.spec for specfile.
INFO  Specfile saved at: /home/barry/rpmbuild.d/k/SPECS/python-xml-preferences.spec.
INFO  Starting rpmbuild to build: /home/barry/rpmbuild.d/k/SPECS/python-xml-preferences.spec SRPM.
INFO  b'setting SOURCE_DATE_EPOCH=1608422400\nWrote: /home/barry/rpmbuild.d/k/SRPMS/python-xml-preferences-1.1.5-1.fc33.src.rpm'
INFO  That's all folks!

**Comment by gordonmessmer** [comment]
We could solve this like #253
