### ISSUE TITLE
Travis CI should be migrated to travis-ci.com

### ISSUE THREAD

**Issue by gordonmessmer** [fedora-python/pyp2rpm#257]
The existing travis-ci.org integration will shut down soon.

I don't seem to have access to this, perhaps because I'm an outside collaborator?

**Comment by hroncok** [comment]
I've invited you to the group.

**Comment by gordonmessmer** [comment]
That doesn't seem to have resolved the issue.  I'm looking at Github's documentation, and from what I gather, this permission is set at the org level, which does explain why I can't add the application.

https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/adding-github-app-managers-in-your-organization#giving-someone-the-ability-to-manage-an-individual-github-app

**Comment by hroncok** [comment]
Granted gordonmessmer permission to manage GitHub Apps owned by this organization

(But I cannot seem to enable travis-ci.com here either.)

**Comment by hroncok** [comment]
https://travis-ci.com/github/fedora-python/pyp2rpm/ seem to exist now \o/
