### ISSUE TITLE
Version detection is broken

### ISSUE THREAD

**Issue by fabaff** [fedora-python/pyp2rpm#262]
A long the way the version detection broke down...my guess is that due to the changes intruduced by replacing the XMLRPC client with the JSON API client (#247).

One don't get the latest version but the first.

Work-around is to use `-v`. Requires to know what the latest version is.

**Comment by gordonmessmer** [comment]
3.3.6 should be on pypi and in the fedora updates-testing repos.  Please let me know if that doesn't resolve the issue.
