### ISSUE TITLE
installation in virtualenv fails

### ISSUE THREAD

**Issue by marbu** [fedora-python/pyp2rpm#27]
When I try to install current master of pyp2rpm in virtualenv, it fails with strange error (full output is here https://gist.github.com/marbu/1457a683fe5bac9e47d4).

This is not pyp2rpm issue, the root cause seems to be in `pypandoc` module (maybe related to [sloppy error handling](https://github.com/bebraw/pypandoc/issues/86)) which is used by `setuptools-markdown`, which is used by `virtualen-api`.

Maybe we may ask [virtualenv-api](https://github.com/sjkingo/virtualenv-api) upstream to drop `setuptools-markdown` build dependency, since you can't run it's `setup.py` wihtout pandoc, which makes haskell stack a build requirement.

**Comment by hroncok** [comment]
Thanks for this and lots of upstream issues. I think the most important is this one:

https://github.com/sjkingo/virtualenv-api/issues/21

**Comment by hroncok** [comment]
sjkingo/virtualenv-api#21 should be fixed now
