### ISSUE TITLE
pyp2rpm autobuild generates a very old version instead of the latest one

### ISSUE THREAD

**Issue by Umeaboy** [fedora-python/pyp2rpm#288]
I successfully built autobuild using the spec file that py2rpm created, but I find it odd that 3.8.1 isn't used.

I don't know how to fix this, but someone here might.

**Comment by Umeaboy** [comment]
I use Mageia 8 and latest installed version is pyp2rpm-3.3.5-1.mga8 according to rpm -qa pyp2rpm.

I know for a fact that Mageia 9 will have the latest version of py2prpm, namely 3.3.8.
However I don't know if that fixes the problem as it isn't mentioned in the changelog here.

**Comment by Umeaboy** [comment]
Latest version of autobuild is 3.8.1 according to:

https://pypi.org/project/autobuild/

**Comment by Umeaboy** [comment]
[autobuild.txt](https://github.com/fedora-python/pyp2rpm/files/10095322/autobuild.txt)

The spec file that pyp2rpm created for autobuild

**Comment by gordonmessmer** [comment]
Yes, I believe that will be the result of issue #251 ,  which was fixed in release 3.3.6.  Until you are able to update, you should be able to use the `-v` argument to specify a version.
