### ISSUE TITLE
make compatible interface with stdeb

### ISSUE THREAD

**Issue by mcyprian** [fedora-python/pyp2rpm#3]
It will really help Python folks if various converters from PyPI to native package format had compatible interfaces.

I like the way `stdeb` provides functionality split between command line tools. It is very intuitive: https://pypi.python.org/pypi/stdeb

It will be convenient to have the same stuff for py2rpm. Editing `stdeb` description:
-  pypi-download will query the Python Package Index (PyPI) for a package and download it.
-  pypi-install will query the Python Package Index (PyPI) for a package, download it, create a .rpm from it, and then install the .rpm.
-  py2spec will convert a distutils-built source tarball into a Fedora source package.
-  py2rpm will convert a distutils-built source tarball into a Fedora source package and then use the Fedora machinery to build a .rpm file from this.

---
- Bitbucket: https://bitbucket.org/bkabrda/pyp2rpm/issue/19
- Originally reported by: anatoly techtonik
- Originally created at: 2014-10-26T21:42:07.426

**Comment by hroncok** [comment]
I don't think this will happen in any reasonable future, as this would need many changes of the way the interface works now. Also pyp2rpm doe snot build binary RPMS by the KISS principle. Closing as wontfix, feel free to reopen if you are willing to work on it.
