### ISSUE TITLE
pyp2rpm should not prefer non-linux wheels over zips/tars

### ISSUE THREAD

**Issue by TC01** [fedora-python/pyp2rpm#32]
I looked into packaging [pypandoc](https://pypi.python.org/pypi/pypandoc/1.1.3) for Fedora (because I started using it to parse my markdown READMEs into RST when uploading to PyPI), so I ran `pyp2rpm`.

I was somewhat surprised when it gave me the following for Source0:

```
%global pypi_name pypandoc

Name:           python-%{pypi_name}
Version:        1.1.3

[...snip...]

Source0:        https://pypi.python.org/packages/cp27/p/%{pypi_name}/%{pypi_name}-%{version}-cp27-none-macosx_10_5_x86_64.whl
```

In this particular case, the wheels for pypandoc include a prebuilt pandoc for Mac OSX or Windows. That's probably not what we want to be packaging from so I _think_  we'd probably want to grab [the zip archive instead](https://pypi.python.org/packages/source/p/pypandoc/pypandoc-1.1.3.zip#md5=771f376bf9c936a90159cd94235998c2).

So I could be wrong, but I think pyp2rpm should prefer the tarball/zip formats over a wheel if the wheel is not Linux native. If I have time over the next week I might look into submitting a PR, assuming this is indeed considered incorrect behavior. :)

**Comment by mcyprian** [comment]
At this moment prefered archive is .tar.gz, if tar is not available first file from the list is grabbed. You are right, we should prefer zip in case tar is missing. I have made more changes in package_getters module in bdist_devel branch so I will fix this there and merge it to master with other changes.
