### ISSUE TITLE
Overview of workflow

### ISSUE THREAD

**Issue by mcyprian** [fedora-python/pyp2rpm#4]
From [this thread](https://bitbucket.org/bkabrda/pyp2rpm/issue/18/nameerror-global-name-filenotfounderror-is#comment-13241226). The package building workflow needs a diagram. [Here is the one](http://interactive.blockdiag.com/?compression=deflate&src=eJx1kDEOwjAMRXdOYWVPOABSh-5IiBukiRWFNE2UFgYQd8dpK1HArH5-31_u-mSC9drBYwcg5ABZm6AdDjqiANmAaLYjNWY04vBvt-Ro8TYVxP1WmnRR7k7arwdSjmSxp4pRFdVrVWSKzFZ79b2F8-m49OJDPjdh7fJWZx7pGUvIF6CErk5YaFIuLAjp4gk8X5vtaPM)

---
- Bitbucket: https://bitbucket.org/bkabrda/pyp2rpm/issue/20
- Originally reported by: anatoly techtonik
- Originally created at: 2014-10-27T18:32:57.388

**Comment by rkuska** [comment]
We will use this issue to improve our readme.
