### ISSUE TITLE
sh: TODO:: command not found

### ISSUE THREAD

**Issue by xsuchy** [fedora-python/pyp2rpm#41]
There appear mysterious output:

>   sh: TODO:: command not found

I'm not exactly sure how much this is bug, or some kind of feature, but I would bet on the bug.
Full output:

```
$ LC_ALL=C.UTF-8 pyp2rpm dictime --srpm  -b 2 
INFO  Pyp2rpm initialized.
INFO  Using /home/msuchy/rpmbuild/SOURCES as directory to save source.
INFO  Downloaded package from PyPI: /home/msuchy/rpmbuild/SOURCES/dictime-0.0.2.tar.gz.
INFO  Getting metadata from PyPI.
INFO  Using default template: fedora.spec.
INFO  Using name: python-dictime.spec for specfile.
INFO  Specfile saved at: /home/msuchy/rpmbuild/SPECS/python-dictime.spec.
INFO  Starting rpmbuild to build: /home/msuchy/rpmbuild/SPECS/python-dictime.spec SRPM.
sh: TODO:: command not found
sh: TODO:: command not found
INFO  Wrote: /home/msuchy/rpmbuild/SRPMS/python-dictime-0.0.2-1.fc23.src.rpm
INFO  That's all folks!
```

**Comment by mcyprian** [comment]
It seems that license was not extracted properly:
./mybin.py dictime -b 2 | grep "TODO"           (pyp2rpm v2.0)
License:        ASL %(TODO: version)s

New metadata extractor works better in this case:
pyp2rpm dictime  -b 2  | grep "License"         (pyp2rpm v3.0)
License:        Apache v2
