### ISSUE TITLE
Package "django4facebook" could not be found on PyPI.

### ISSUE THREAD

**Issue by xsuchy** [fedora-python/pyp2rpm#43]
Although there is: https://pypi.python.org/pypi/django4facebook/0.1.0
I get this output:

```
pyp2rpm django4facebook --srpm -d /tmp/tmpROdC8J -b 2
INFO  Pyp2rpm initialized.

INFO  Pyp2rpm failed. See log for more info.
Package "django4facebook" could not be found on PyPI.
```

**Comment by mcyprian** [comment]
This is not pyp2rpm issue, Releases of this package can't be found  through [PyPIXmlRpc API](https://wiki.python.org/moin/PyPIXmlRpc)

In [17]: client.package_releases('django4facebook')
Out[17]: []

In [22]: client.search({'name':'django4facebook'})
Out[22]: []

**Comment by xsuchy** [comment]
Can you forward it to PyPIXmlRpc API team then, please?

**Comment by mcyprian** [comment]
Sure, I have opened an issue https://bitbucket.org/pypa/pypi/issues/433/pypixmlrpc-api-failure.
