### ISSUE TITLE
Stop specialcasing packages with "py" in name on Fedora

### ISSUE THREAD

**Issue by mcyprian** [fedora-python/pyp2rpm#5]
Historically, we specialcased packages with "py" in name on Fedora, as they were named just "pypackagename", not "python-pypackagename". This is no longer true and all packages in Fedora have to be named in form "python-pypackagename" (unless they end with "-python", IIUC) [1]. pyp2rpm should reflect this change (e.g. `pyp2rpm -n py` should yield python-py spec/name/...).

[1] https://fedoraproject.org/wiki/Packaging:NamingGuidelines#Addon_Packages_.28python_modules.29

---
- Bitbucket: https://bitbucket.org/bkabrda/pyp2rpm/issue/23
- Originally reported by: Slavek Kabrda
- Originally created at: 2014-10-31T09:08:43.552

**Comment by mcyprian** [comment]
I played with pyp2rpm naming.

```
#!

pyp2rpm -n python-admob -p 3


%global pypi_name python-admob

Name:           python-%{pypi_name}

%package -n     python3-%{pypi_name}

```

I will try fix those too along with py specialcasing.

---

Original comment by: Robert Kuska

**Comment by mcyprian** [comment]
```
    Hi, this failure occurs because pyp2rpm doesn't expect package to have
    two modules in package root folder, as is beets and beetsplug in your
    case.

    This is of course not a feature and I will try to address this issue in
    next future release, which will come soon.

    Meanwhile you can add to your specfile under %file section
    %{python_sitelib}/beetsplug manually.
```

---

Original comment by: Robert Kuska

**Comment by mcyprian** [comment]
Testers are needed and welcomed.  :-)

---

Original comment by: Robert Kuska

**Comment by mcyprian** [comment]
pyp2rpm now when generating (Build)Requires changes pytest into python-pytest and we have no such package in fedora pkgdb.

I reopen this again to track this.

I have basically two ideas how to deal with this; use list of most common pyfoo named packages already in fedora pkgdb and skip 'rpmizing' their names or wait until pyfoo packages will provide python-pyfoo.

---

Original comment by: Robert Kuska

**Comment by rkuska** [comment]
This should be resolved in Fedora. Closing this.
