### ISSUE TITLE
PyPI changed the download URL format

### ISSUE THREAD

**Issue by torsava** [fedora-python/pyp2rpm#50]
Hi, PyPI recently completely changed the format of download links, therefore I suggest switching to the new URL format:

```
https://files.pythonhosted.org/packages/source/p/positional/positional-1.1.0.tar.gz
```

This new format should have a long term support: https://bitbucket.org/pypa/pypi/issues/438/#comment-27734791

Further discussion: https://bitbucket.org/pypa/pypi/issues/438/#comment-27734791

**Comment by hroncok** [comment]
Note: Currently pyp2rpm adds the new hashed URL in the Source filed.

**Comment by torsava** [comment]
Right. Updating to the above mentioned URL format is advisable because when updating the package to a new version, you only need to change the Version: tag and the URL will work, whereas with the hashed URLs you need to manually go to PyPI and copy the new URL each time.
