### ISSUE TITLE
testing: disable network

### ISSUE THREAD

**Issue by glensc** [fedora-python/pyp2rpm#57]
please allow running tests that do not require network

so i could enable basic testing in distro build environment where network access is not permitted

**Comment by hroncok** [comment]
I see that in Fedora, this is done in not very clean way:

http://pkgs.fedoraproject.org/cgit/rpms/pyp2rpm.git/tree/rm_url_test.patch

I suggest we use a marker, like `@pytest.mark.webtest`

**Comment by hroncok** [comment]
@glensc Do you happen to have list of tests that fail with no network?

**Comment by glensc** [comment]
[NjUN.txt](https://github.com/fedora-python/pyp2rpm/files/334849/NjUN.txt)

but it's mixed with other errors not just network errors

**Comment by mcyprian** [comment]
The only test that doesn't work for me without network connection is test_get_url, I added @pytest.mark.webtest to it in 3fc59dabcc3671.
