### ISSUE TITLE
Unnecessery parsing of test_requires

### ISSUE THREAD

**Issue by xsuchy** [fedora-python/pyp2rpm#61]
I run:

```
pyp2rpm tempest-lib
```

which results in:

```
BuildRequires:  sphinx < 1.3
BuildRequires:  sphinx >= 1.1.2
```

as this is impossible to satisfy in fedora-rawhide, I investigated from where this comes.

It is put there because tempest-lib has `test-requirements.txt`, which a) outdated b) actually not needed, because produced spec file does not have any `%check` section. a) is beyond pyp2rpm, but b) should be addressed by pyp2rpm.

It comes from:

```
    def build_deps(self):
        build_requires = self.get_requires(['build_requires', 'test_requires'])
```

where test_requires are added unconditionally. It should be added only if there are some tests.

**Comment by xsuchy** [comment]
Hmm that will be not enough. These test requirements get there just after

```
  extract_distribution.run_setup(setup_py, 'bdist_rpm')
```

so the change will be probably much harder.

**Comment by mcyprian** [comment]
^ This commit shouldn't be here I wrote number 61 instead of 62 to the commit message.

**Comment by mcyprian** [comment]
After [refactoring of metadata_extractors](https://github.com/fedora-python/pyp2rpm/pull/77) %check section is included each time test_requires are not [empty](https://github.com/fedora-python/pyp2rpm/commit/9c67fa1f71bb11b0dff157bab3f0fc07e20a8282#diff-b03f151d580cccef91f5d2c92a70977aR353) or 'test_suite' is specified in setup.py script. Unfortunately we can't find more reliable way to determine if package contains tests or not.
