### ISSUE TITLE
package rename option is ignored - importing Sphinx package with wrong name

### ISSUE THREAD

**Issue by ssbarnea** [fedora-python/pyp2rpm#87]
While trying to convert one of the most popular python packages `Sphinx` I found this bug.

    pyp2rpm -r python-sphinx -d . --srpm Sphinx

Instead of generating a rpm for the package named `python-sphinx` it will generate `python-Sphinx`. Both filename and NAME-VERSION-RELEASE do contain `python-Sphinx` instead of `python-Sphinx`.

Base on Fedora naming convention I would even assume that the package name would be lowercases anyway, but that's not the case. 

I would not mind making a pull request but first I want to understand which approach for fixing this would be preferred.

**Comment by mcyprian** [comment]
We should take a loot at #66 before fixing this issue. It is also related to pypi_name macro usage in the template.
